### ISSUE TITLE
Tab unread counter doesn't work on all services

### ISSUE THREAD

**Issue by kr3t3n** [ramboxapp/community-edition#2008]
### Steps to reproduce

1. Enable services like GMail, MS Teams, Roundcube
2. Receive new message/email
3. Tab counter is not showing

### Expected behavior

I expect the services to show unread messages/emails like the others do, like Hangouts, LinkedIn, WhatsApp, etc.

### Actual behavior

Rambox unfortunately does not show tab counter for unread messages for the services listed above (GMail, MS Teams, Roundcube)

### ENVIRONMENT

Windows 10

> Rambox: v0.6.3

> OS: Windows 10

> Arch: x64

**Comment by kr3t3n** [comment]
> 
> 
> Gmail & Roundcube works for me 🤔
> 
> But for MS Teams, i have opened a new issue #2020 with a PR #2021
> Paste this in Teams custom code in the meantime :
> 
> ```js
> function checkUnread() { 
>    updateBadge(angular.element(document.documentElement).controller().pageTitleNotificationCount);
> }
> function updateBadge(e){
>    e>=1 ? rambox.setUnreadCount(e) : rambox.clearUnreadCount()
> }
> setInterval(checkUnread,3000);
> ```

Any idea what I could do to force Gmail & Roundcube to work for me too?

**Comment by maxerbox** [comment]
Gmail Fixed in #2034

**Comment by kr3t3n** [comment]
GMail and Teams work now but Roundcube still doesn't. Any clue how to fix that?
