### ISSUE TITLE
Outlook 365 does not  display notifications anymore, after their new design version

### ISSUE THREAD

**Issue by cnotv** [ramboxapp/community-edition#2114]
Since a couple of months Outlook 365 has been redesigned and new messages are not notified anymore. 
OS: Ubuntu 18.04.2 LTS

**Comment by prydonius** [comment]
Also seeing this issue, desktop notifications in the new Outlook work fine in Chrome but not in Rambox.

**Comment by Corchoneitor** [comment]
We'll have a look at O365 notification.

> Also seeing this issue, desktop notifications in the new Outlook work fine in Chrome but not in Rambox.

Fixed in d619a66

**Comment by loganbest** [comment]
That looks like it was fixed for live.com service, not office.com service. I just tried the one listed in the commit diff for that commit and it doesn't work for Outlook 365 service.

**Comment by relaytheurgency** [comment]
Looks like this change was released in 0.6.9 but I'm still not getting notifications for my business office 365 outlook.
