### ISSUE TITLE
Rambox Keyboard Shortcuts no longer working from within services

### ISSUE THREAD

**Issue by lanceofwhichwedream** [ramboxapp/community-edition#2164]
Rambox specific shortcuts no longer appear to be working when in a service's tab.

Reproduction steps:
Open rambox, go into a service (discord, messenger, slack whatever) attempt to switch to another service using CRTL + Number of the service.

	
	-
	> Rambox 0.6.4
	> Electron 3.1.4
	> win32 x64 10.0.17763

**Comment by parabolic** [comment]
Same, here, rambox productivity dropped because of no being able to:
-  zoom in/out ( CTRL + '-/+') 
- rotate through services CTRL + pageup/pagedown.

I've used those in conjuction with slack shortcuts to be as productive as possible but I am unable to use them anymore. I have noticed a behaviour that might help in pinpointing this bug. When I try to zoom in a window only the rightmost service gets zoomed in/out in the background.
```
Version: 0.6.4
Platform: linux (x64)
Electron: 3.1.4
Chromium: 66.0.3359.181
Node: 10.2.0
```

**Comment by khalilayache** [comment]
Same here!

**Comment by maxerbox** [comment]
Working on pageup & pagedown

**Comment by maxerbox** [comment]
Fixed pageup-pagedown-zoomin-zoomout issue

**Comment by sloneorzeszki** [comment]
Still not working for me. Linux Mint, Rambox installed via snap - could this be a problem?

**Comment by maxerbox** [comment]
0.6.5 Not released yet

**Comment by russelldavies** [comment]
Did this not make its way into 0.6.6?

**Comment by maxerbox** [comment]
Nope, it was added in 0.6.5

**Comment by russelldavies** [comment]
I've just tried 0.6.5 and it's still not working. Also still not working 0.6.6:
```
Version: 0.6.6
Platform: darwin (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0
```

**Comment by maxerbox** [comment]
If it's not related to #2212, open a new issue please

**Comment by youlogix** [comment]
Not working for me as well. Basic commands like ⌘ + C or ⌘ + V are not working.

**Comment by emmandichoso** [comment]
Same here, keyboard shortcuts not working.

**Comment by emmandichoso** [comment]
The issue was the keyboard shortcut ⌘ + V mapped to "Paste and Match Style". Also, not working for BTT shortcut.

Removed and now working. Looking for an alternative to paste non-formatted text.

**Comment by emmandichoso** [comment]
Shortcut ⌘ + V mapped to "Paste and Match Style" is working on other macOS apps if disabled on Rambox. 

@maxerbox Is it possible that this is because Rambox is using "⌘ + ⌥ + V " vs "⌘ + ⇧ + V" used in macOS? Thanks!
