### ISSUE TITLE
MacOS: Unread slack messages not shown on dock icon

### ISSUE THREAD

**Issue by Nastase** [ramboxapp/community-edition#2239]
### Steps to reproduce

1. Rambox running either on background or minimized
2. Receive messages on Slack

### Expected behavior

The dock icon should change to show the unread message counter or update the counter if already visible.
The dock icon should bounce when corresponding option is checked in preferences.

### Actual behavior

The standard message notification is shown but the dock icon is not updated and the icon doesn't bounce. If the unread messages counter is not displayed on the icon before the messages come, the counter is not displayed; if the counter is already displayed it is not updated.

### ENVIRONMENT

> Rambox: v0.6.6

> OS: MacOS 10.14.4

> Arch: x64

**Comment by Nastase** [comment]
Some more info:

Tested again now and when receiving a message, if focus is given to Rambox, the Slack tab if updated with the unread counter (after a short delay and only after focus if given to Rambox) and the unread counter on the dock icon starts blinking: it shows for 1 seconds and then is hidden for 3 seconds.

**Comment by Corchoneitor** [comment]
Hi @Nastase!

Can you update to 0.6.7? There was an error related to this, that was fixed. Let's see if it fixes yours too.

https://github.com/ramboxapp/community-edition/releases/tag/0.6.7

**Comment by Nastase** [comment]
Hi @Corchoneitor 

I'm on 0.6.7 and the problem still persists.

**Comment by anky2209** [comment]
I am also on 0.6.7 and this issue persists.

Rambox Info:
```
Version: 0.6.7
Platform: darwin (x64)
Electron: 4.1.4
Chromium: 69.0.3497.128
Node: 10.11.0
```

**Comment by Corchoneitor** [comment]
Hi guys.

I'll test this on a VM, In the meantime, please update manually to [v0.6.9](https://github.com/ramboxapp/community-edition/releases/tag/0.6.9).
