### ISSUE TITLE
Unable to login to google account with 2-step verification

### ISSUE THREAD

**Issue by cjayyy** [ramboxapp/community-edition#2521]
![rambox-google-2FA-login](https://user-images.githubusercontent.com/14090214/70621418-93143280-1c2a-11ea-9d61-217028ddee5f.png)

### The issue 
When trying to log in to an google account (tried Gmail, Keep, Calendar) with 2FA, the form keeps loading at 3rd step (after providing password). Loading never stops. 

### Steps to reproduce the issue 
1. Login to any google service via account with 2FA enabled. 

### Tried these to fix
1. Uncheck "Disable Hardware Acceleration".
2. Restart Rambox.

	-
	> Rambox 0.7.2
	> Electron 7.1.1
	> linux x64 4.15.0-70-generic

_**UPDATE: After waiting couple of minutes the process failed and offered me an alternative way of authenticating (expected behaviour). Therefore this issue is about response taking too long rather than no response at all.**_

**Comment by Sphiinx** [comment]
The past few days I keep getting "You are trying to sign in from a browser or app that doesn't allow us to keep your account secure."

It didn't happen before and I've always had 2FA enabled. I tried disabling 2FA and turning off hardware acceleration and nothing works.

![Screen Shot 2019-12-11 at 10 31 49](https://user-images.githubusercontent.com/11341771/70645145-a52dab00-1c01-11ea-8884-54d2d8893a34.png)

**Comment by delphym** [comment]
I believe this issue has been fixed in Rambox v0.7.3

**Comment by cJayyy** [comment]
Unfortunately it hadn't. 
Version 0.7.3 addresses different google login issue. It looks like these are independent on each other. 

This issue persists in Rambox v0.7.3.

**Comment by fvulich** [comment]
I just checked adding a new Gmail service, then tried to log in with an account that has 2FA (SMS) and worked as it should (Rambox 0.7.3)

**Comment by cJayyy** [comment]
I am actually not using an SMS but the phone request (where you just approve log-in by pushing "_Yes_" or "_No_"). I don't know how is this feature called but I think it is has native support from Android - **I am not talking about Authenticator app**.  

Perhaps the problem could be that every time I am logging into the Google accounts the 2FA tries to automatically find and use the key. I don't have a key so I have to wait until this fails and choose to try it using different method. That where I choose I want to authenticate by the phone confirmation.

**Comment by compuguy** [comment]
I'm having a similar issue, but it is stuck waiting for me to connect my U2F dongle. After several minutes It eventually asks me to try an alternative 2FA method, similar to what @cJayyy experienced.

**Comment by LivingWithHippos** [comment]
I have this problem too on kubuntu. What I noticed by reloading several times  is that google sends you to an [error page](https://support.google.com/accounts/answer/7675428?hl=en) that gives this as a possible reason: 
To help protect your account, Google doesn’t let you sign in from some browsers. Google might stop sign-ins from browsers that: 
- Are embedded in a different application.
```
uname -a
Linux user-hp 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
```
	-
	> Rambox 0.7.3
	> Electron 7.1.1
	> linux x64 5.0.0-38-generic

**Comment by pconwell** [comment]
Are you using Google's Advanced Protection? Or just 2FA?

- [Advanced Protection](https://landing.google.com/advancedprotection/)
- [2-Step Verification](https://www.google.com/landing/2step/)

I just now logged into my Gmail account using my Yubikey key in Rambox 0.7.3. I did not have any issues. When I signed in, I entered my username and password then it asked for my U2F key. I plugged it in, hit the button and it signed me in.

I'm on Windows 10.

**Comment by LivingWithHippos** [comment]
I uninstalled python3 and removed Rambox by mistake (damn apt --purge). I installled Rambox again, from the zip instead of the snap image and tried again, I have the same issue.
I use the 2FA, I didn't even know of advanced protection.

**Comment by pconwell** [comment]
@LivingWithHippos hmm... I tried in Windows (see above) and it worked fine for me. I just now tried it in Linux Mint (Debian/Ubuntu) with the following steps:

```
$ cd ~/Downloads
$ wget https://github.com/ramboxapp/community-edition/releases/download/0.7.3/Rambox-0.7.3-linux-amd64.deb
$ sudo dpkg -i Rambox-0.7.3-linux-amd64.deb 
```

I was able to sign in without any issues using U2F Yubikey.

**Comment by LivingWithHippos** [comment]
A strange thing I noticed is that it does the same without the key inserted. 
I download the yubikey manager and it does not work, I get the error
`qml: refreshing devices failed: 'Failure to establish context: Service not available` which brings me to [this issue.](https://github.com/Yubico/yubioath-desktop/issues/78) 
I'll try to fix that and report, maybe it's a problem on yubikey side.

**Comment by pconwell** [comment]
@LivingWithHippos, I just confirmed that I'm on the same versions as you:

```
Version: 0.7.3
Platform: linux (x64)
Electron: 7.1.1
Chromium: 78.0.3904.99
Node: 12.8.1
```

Looks like we are on the same versions, so I'm not sure why you are having issues. The only suggestion I have is to try the .deb package - though I don't really know why that would make a difference seeing as they are the same versions.

**Comment by LivingWithHippos** [comment]
I'm 99% sure this is an issue on yubikey side and has nothing to do with RamBox, I tried to login into a google account using ungoogled-chromium and had the same issue.

I also found these issues and it sounds like my problem. It should be fixed "soon".
* https://github.com/Yubico/yubioath-desktop/issues/498
* https://github.com/Yubico/yubioath-desktop/issues/491

**Comment by pconwell** [comment]
Interesting. I don't even have Yubikey Authenticator (or any Yubikey software at all) installed and it worked just fine for me.

**Comment by mrfloppi** [comment]
Are there any news on this issue? I've recently switched to two factor authentication and now I can't use Rambox anymore because it's not possible to log into any Google Service.

**Comment by LivingWithHippos** [comment]
My case is a little different because I have a hardware key, but I noticed on Windows that rambox hides the browser notification asking to touch it. 
If you have a yubico you can test it on the [playground](https://demo.yubico.com/playground) and while on the standard browser you get shown something like this 
[![yubico-notification.png](https://i.postimg.cc/prCFFb5v/yubico-notification.png)](https://postimg.cc/tn1TKczv) 

nothing get shown on Rambox. 

When you try and log in to google/gmail you just have to press the key when it flashes, it's not actually stuck. 

For other methods of 2fa, I can't help. I also still have to test this in Linux but I think it's a standard Rambox behaviour.

**Comment by fvulich** [comment]
We are investigating this issue. We really appreciate all the information that you share with us.

**Comment by tomasgeci** [comment]
I'm experiencing same issue on Xubuntu 18.04.4 64bit and rambox 0.7.4 or 0.7.5 stable installed via snap. Yubikey works without any problem in firefox/chrome browser but not in Rambox.

In case if you need some further information/log/whatever, please let me know I'll try to provide.

**Comment by pconwell** [comment]
@tomasgeci this seems to be a bizarre issue as some people are affected and others aren't. I, for example, have had no issues on Windows or Ubuntu. Could you try something just for kicks?

See if you can install the deb package instead of snap and see if that makes a difference:

```
$ cd ~/Downloads
$ wget https://github.com/ramboxapp/community-edition/releases/download/0.7.5/Rambox-0.7.5-linux-amd64.deb
$ sudo dpkg -i Rambox-0.7.5-linux-amd64.deb
```

**Comment by tomasgeci** [comment]
@pconwell many thanks, from package it works like a charm :-) 
Now I have idea where is the problem. DEB version works as expected but snap not. It could be some misconfiguration in snap manifest - some security configuration, because snap not always allows access to any peripheral or location.
I'm not deeply involved in snap package system, but there should be some security directive which allows acces to peripherals like U2F.

**Comment by isviridov** [comment]
I've the same issue, though probably a worse incarnation.
I'm on Mac (MacOS 10.14.6); Rambox 0.7.5 (same issue with 0.7.3).
I've security key (and google authenticator, and other 2FA mechanisms) enabled; I'm getting Google offer to use security key; it never times out  to offer other 2FA options (as it does in a regular browser), staying stuck at the screenshot attached.
If i've security key handy, it does indeed work as designed; but other 2FA mechanisms are not available, which is occasionally a pain.
![Screen Shot 2020-03-29 at 20 57 33 ](https://user-images.githubusercontent.com/761508/77874161-ff7a6800-7200-11ea-9871-be2e945b8e53.png)

**Comment by abampalexnder** [comment]
> I'm having a similar issue, but it is stuck waiting for me to connect my U2F dongle. After several minutes It eventually asks me to try an alternative 2FA method, similar to what @cJayyy experienced.

I have got solution for google after 3 weeks brain storming and spent all day and night time to resolve the issue 

any one need solution can contact on wire @abampalxender
19 Apr 2020

**Comment by abampalexnder** [comment]
> I've the same issue, though probably a worse incarnation.
> I'm on Mac (MacOS 10.14.6); Rambox 0.7.5 (same issue with 0.7.3).
> I've security key (and google authenticator, and other 2FA mechanisms) enabled; I'm getting Google offer to use security key; it never times out to offer other 2FA options (as it does in a regular browser), staying stuck at the screenshot attached.
> If i've security key handy, it does indeed work as designed; but other 2FA mechanisms are not available, which is occasionally a pain.
> ![Screen Shot 2020-03-29 at 20 57 33 ](https://user-images.githubusercontent.com/761508/77874161-ff7a6800-7200-11ea-9871-be2e945b8e53.png)

I have got solution for google after 3 weeks brain storming and spent all day and night time to resolve the issue 

any one need solution can contact on wire @abampalxender
19 Apr 2020

**Comment by abampalexnder** [comment]
I have got solution for google after 3 weeks brain storming and spent all day and night time to resolve the issue any one need solution can contact on 
Email: abmpanalexander@protonmail.com
on wire @abampalxender

**Comment by LivingWithHippos** [comment]
It now works correctly for me, I switched from windows 10 ltsb (stuck on 1809) to a "normal" windows edition (1909) and it immediatly shows the popup (like [this](https://mk0boxminingmnwnavp0.kinstacdn.com/wp-content/uploads/2019/05/Windows-Security-Ledger-1024x437.jpg)) asking for the hardware key.

**Comment by johnbarney** [comment]
RamBox 0.7.5 on Windows 10 does not have this issue however Pop_OS 20.04 running RamBox 0.7.5 has this issue using the same Google account and using Yubikey as my 2FA. Other browsers on my Pop_OS device (Chromium, Firefox, Chrome) do allow me to use the Yubikey. Happy to provide additional detail on any of my devices upon request.

**Comment by omata** [comment]
Hello,

I can confirm that the issue is still on going in the latest version for Mac:

```text
Version: 0.7.5
Platform: darwin (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1
```

I had 2FA enabled with a hardware key, _(Google Pixel as a bluetooth Key)_, but Rambos doesn't detect any bluetooth key never. So, I wait expecting it could give me another way to authenticate, but it didn't. I Just closed Rambox and opened again and tried again all the process. This time it let me choose another method. I choose press Yes button in my Android device and it worked, but after this I just got an **OK** message and no more, it is stuck at this stage and nothing else happens. If I close/open Rambox Again It let me choose my already "logged in" Google account but the annoying **OK** message appears again. I'm totally blocked to use Rambox.

![Rambox](https://d.pr/i/BLvyea+)

Regards,

**Comment by vzaliva** [comment]
The issue is still here. 

Version: 0.7.5
Platform: linux (x64)
Electron: 7.1.12
Chromium: 78.0.3904.130
Node: 12.8.1

**Comment by rgarrigue** [comment]
Same here, 2FA using a SoloKeys security keys. The key's led isn't blinking, google web page validation keep on loading forever. It works using chromium & firefox. Rambox's 0.7.5 snap 13 over xubuntu 20.04.

**Comment by reverbsoul** [comment]
Same issues, but in Rambox Pro 1.3.2 installed with snap.

It's only recently started happening so it's possible that this is related to the 1.3.2 update that went live on June 1.

Version 1.3.2 (Pro)
Kubuntu 20.04

Works in all browsers, including Google login within the browser.

**Comment by reverbsoul** [comment]
Hey all, any update here? Having to keep multiple browser tabs with email open essentially negates the need for Rambox Pro.

While I wouldn't mind temporarily disabling my keys to get around this while a fix is being worked on, I unfortunately can not do so as I'm using work emails that require it.

Any information about the investigation that started on Dec 12, 2019 would be greatly appreciated.

Thanks!

**Comment by schmug** [comment]
Sam issues, Fedora Silverblue using rpm-ostree install rpm. Google Chrome works fine but in Rambox, 2-factor security keys takes ~10+ minutes to time out before you can select another factor. Personal or Google Workspace/Gsuite.

**Comment by dougsland** [comment]
> Sam issues, Fedora Silverblue using rpm-ostree install rpm. Google Chrome works fine but in Rambox, 2-factor security keys takes ~10+ minutes to time out before you can select another factor. Personal or Google Workspace/Gsuite.

same here, giving a try with ramboxapp on Fedora 34. After 10minutes or more the page to select other device appeared.

**Comment by andreaskern** [comment]
> > Sam issues, Fedora Silverblue using rpm-ostree install rpm. Google Chrome works fine but in Rambox, 2-factor security keys takes ~10+ minutes to time out before you can select another factor. Personal or Google Workspace/Gsuite.
> 
> same here, giving a try with ramboxapp on Fedora 34. After 10minutes or more the page to select other device appeared.

same here. I'm using the Appimage on fedora and while I'm waiting for the 10minutes to pass I'm writing this reply 🤷

**Comment by delphym** [comment]
I'm having a closer look now.... Will update once I run it and monitor over
a longer period of time.
But so far it seems good.
Thanks

**Comment by rasatpetabit** [comment]
It looks like this is still a serious ongoing issue.
