### ISSUE TITLE
Microsoft Teams: Screen Share not working

### ISSUE THREAD

**Issue by DennisGaida** [ramboxapp/community-edition#2655]
### Steps to reproduce

1. Join a meeting in Microsoft Teams
2. Try to share your screen
3. The "Share screen" button does nothing

### Expected behavior

In a regular browser the "Share screen" button opens a popup where I can select what I want so share, see the following screenshot:
![Untitled-1](https://user-images.githubusercontent.com/2392217/78028592-90675580-735f-11ea-8ab0-b05cac119edb.png)

### Actual behavior

The share screen / application button does not open a popup nor does it share the screen or a window.

### ENVIRONMENT

> Rambox: v0.7.5
> OS: Win10
> Arch: x64

**Comment by trulex** [comment]
Same on Linux.

**Comment by fvulich** [comment]
In order to get this work we need a chrome's extension. We are investigating on how to make it work.

**Comment by DennisGaida** [comment]
Out of interest - is this because of running within Electron? I can't make out any particular Microsoft Teams extension for this to work or maybe it is hidden?

**Comment by fvulich** [comment]
I checked again, and they seem to have changed the way that they share screen, but it still doesn't work. We're investigating it... Please, share with us any information that seems relevant for you.

**Comment by joschi127** [comment]
Maybe interesting to know: Teams Screen Sharing also does not work for Rambox Pro or for Franz. 

**But it seems to be working** with https://github.com/ivelkov/teams-for-linux which is also Electron based.

(I first though it might be related to the user agent. But the unofficial teams-for-linux client is using `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) teams-for-linux/1.0.0 Chrome/69.0.3497.128 Electron/4.2.8 Safari/537.36` as a user agent and at least when setting the same for Rambox Pro it doesn't help. Still not working.)

**Comment by joschi127** [comment]
Maybe this is doing the trick: https://github.com/IsmaelMartinez/teams-for-linux/blob/736c3cf475b716951124f9f1431202f57e07c6f1/app/browser/index.js#L17

**Comment by DennisGaida** [comment]
Good find @joschi127 ! https://github.com/IsmaelMartinez/teams-for-linux/tree/master/app/browser/desktopShare this really seems to do the trick with a custom HTML popup for selecting the screen capture.

**Comment by rauldipeas** [comment]
No service share the screen in Rambox, i’ve already tested several.

**Comment by joschi127** [comment]
@DennisGaida Maybe also this part? https://github.com/IsmaelMartinez/teams-for-linux/blob/736c3cf475b716951124f9f1431202f57e07c6f1/app/browser/index.js#L38

**Comment by joschi127** [comment]
Sneak preview: It is possible.
Managed to get a (currently still very hacky) version running:

![image](https://user-images.githubusercontent.com/1758468/81346845-4d657400-90bb-11ea-9b88-a62b43b282f5.png)

![image](https://user-images.githubusercontent.com/1758468/81346907-7128ba00-90bb-11ea-94c7-a7249bab44fa.png)

**Comment by IsmaelMartinez** [comment]
Please fire any questions around if you have to. Only realised now when you ping me. It works and being working for a good while so I am happy to help.

**Comment by saenzramiro** [comment]
Thank you @joschi127 and @IsmaelMartinez! We will wait your PR to add it to the next version.

**Comment by joschi127** [comment]
Stay tuned... I did not forget. But not much progress yet cleaning the code up, because if limited time :)

**Comment by coreyemmons** [comment]
Just wanted to comment and let you know that I appreciate the work going in to fixing this issue... it's the only thing keeping me from uninstalling the Teams desktop client. Looking forward to the fix!

**Comment by RauchF** [comment]
Do you know if the changes done here will also affect other meeting services like Google Meet? I've noticed screen sharing also does not work there currently. Or should I create a new issue for that? Really appreciate your work :)

**Comment by fbarbare** [comment]
Is this still being worked on? Is there a branch for it?
If you need a hand I might be able to help. That's the only thing I'm missing in Rambox

**Comment by joschi127** [comment]
@RauchF I think that based on the changes it should also be possible to make this work for other services. But at least parts of the implementation are MS Teams specific. So at least a bit more work will be needed to adapt it for other services.

@fbarbare  Still on my list but did not find the time yet. It's not pushed to any branch yet.

Hope to find some time soon. Will try .... ;-)

**Comment by CelsoSantos** [comment]
Don't know if this is relevant here as well, but I notice Rambox doesn't ask for "Screen Recording" permissions on MacOS Catalina. However, I'm not sure if it the apps responsibility to ask for these permissions or if thats something that MacOS does by itself once an application tries to use such functionality.

**Comment by timofey** [comment]
Do we have any more updates on this?
Hey, @joschi127 I thought you could push what you already have so we all could help to move it further. Really appreciate your effort in this!

**Comment by avoidik** [comment]
hey @joschi127 mind to provide at least a code snippet on how to enable screen-sharing?

**Comment by joschi127** [comment]
@timofey  There you go - I at least pushed the experimental first hacky version to a fork.

You can find it on this branch:
https://github.com/joschi127/community-edition/commit/420d4c203582059c11179867c664ffafbaf4f71c

Changes are in this commit:
https://github.com/joschi127/community-edition/commit/420d4c203582059c11179867c664ffafbaf4f71c


It is still pretty much WORK IN PROGRESS.
Contains hacky debug output.
Only works when sharing screen for the first time, seems to have some bug when trying for a second time, app restart needed then.

Hope this helps - and let me know if anyone continues working on this!

All credits go to @IsmaelMartinez! - I've only copied from his code ;-)

**Comment by avoidik** [comment]
hey @brad sorry to bother you, would you please take a look and maybe give it a priority higher than zero? :)

**Comment by brad** [comment]
@avoidik I'm no longer a Teams user 🤷

**Comment by gs1-rob-392** [comment]
The problem is not only for Teams, I can't share my screen also with meet, rainbow.
Can you increase the priority of this issue?

**Comment by joaotomasrobalo** [comment]
It doesn't work on Microsoft Teams. I'm on Mac OS.

Is it possible to be because Rambox does't "ask" for permissions to screen record? For example to be able to share my screen on a google meeting (using google chrome for example) I had to grant the google chrome app this permission. 

<img width="667" alt="Screenshot 2021-02-12 at 12 00 50" src="https://user-images.githubusercontent.com/43414610/107765541-f5cef580-6d29-11eb-9876-c41e46e59d07.png">

If I untick any of those apps from the screen recording permissions, the "share screen" will stop working (either on a google meeting on chrome or a zoom call on zoom). I assume Rambox needs to be here for the system to allow screen sharing. 

That permission is a requirement for sure.

Now my assumption that could be wrong. -> The problem is that for us to add Rambox on the granted permissions to screen record apps list, the application needs to "ask" first and it seems not to be happening because I don't see Rambox here, even when I try to share my screen.

Does this makes sense?

**Comment by avoidik** [comment]
@joaotomasrobalo imo, this is the consequences of the electron framework limitations

**Comment by JL102** [comment]
> @/timofey There you go - I at least pushed the experimental first hacky version to a fork.
> 
> You can find it on this branch:
> https://github.com/joschi127/community-edition/tree/feature/screen-sharing
> 
> Changes are in this commit:
> [joschi127@420d4c2](https://github.com/joschi127/community-edition/commit/420d4c203582059c11179867c664ffafbaf4f71c)
> 
> It is still pretty much WORK IN PROGRESS.
> Contains hacky debug output.
> Only works when sharing screen for the first time, seems to have some bug when trying for a second time, app restart needed then.
> 
> Hope this helps - and let me know if anyone continues working on this!
> 
> All credits go to @/IsmaelMartinez! - I've only copied from his code ;-)

@joschi127 How do I get it to run?
I'm using Windows 10 x64, and I have Node v14.15.4 with Electron v11.2.3 installed globally.

I downloaded the contents of that branch as a zip, ran `npm install --save-dev` on the root directory, then ran `electron .`
The Rambox window opened, but the interface didn't load. Is there anything else I have to do?
![image](https://user-images.githubusercontent.com/11487870/108256051-04068280-712b-11eb-808c-0e5578875452.png)

**Comment by IsmaelMartinez** [comment]
Hi all, in the teams-for-linux client I had to recently change the user agent to be an older version (MS has changes something), otherwise it does look like is sharing but the people on the other end don't get the image. 

User agent change in here in case it helps.

https://github.com/IsmaelMartinez/teams-for-linux/commit/7d799b61ff103e0c6e8e04424a4d256756435fe5#diff-535862e0ea81c86515cf420ccacad99b6453c8551c91fe9f4705070595d1d218

**Comment by harimau99** [comment]
i have the same question as @joaotomasrobalo . on MacOSX 10.14 and above seems can't get screenshare.
Is there any existing workaround for this issue?

**Comment by nandez** [comment]
Not sure if this is relevant.. but here is a screenshot of devtools for a Teams tab after clicking on "Share Screen"... one of the error messages states something regarding permissions:

`{"type":"permissionDeniedError","detail":"permission to use media device was denied: NotAllowedError: Permission denied constraints: {\"audio\":null,\"video\":{\"maxWidth\":1920,\"minWidth\":1920,\"maxHeight\":1080,\"minHeight\":1080,\"fps\":15,\"deviceId\":\"u25\"},\"withTimeout\":false}","isAudio":false,"message":"permission to use media device was denied: NotAllowedError: Permission denied constraints: {\"audio\":null,\"video\":{\"maxWidth\":1920,\"minWidth\":1920,\"maxHeight\":1080,\"minHeight\":1080,\"fps\":15,\"deviceId\":\"u25\"},\"withTimeout\":false}"}`

Maybe @joaotomasrobalo is on the right track...

OS: Windows 10 Pro 20H2 - Build. 19042.928 
Rambox: 0.7.7
Platform: win32 (x64)
Electron: 7.2.4
Chromium 78.0.3904.130
Node: 12.8.1
 
![image](https://user-images.githubusercontent.com/1672704/117067480-73d6e300-ad00-11eb-8d8b-6241fc5353de.png)

**Comment by jijojosephk** [comment]
This is due to the new way of screen sharing using latest MediaDevices API. We just need to Override the MediaDevice class methods. This has been fixed in teams-for-linux [https://github.com/jijojosephk/teams-for-linux/tree/issue-432/app](here) fork from [https://github.com/IsmaelMartinez/teams-for-linux] This PR hasn't been merged yet. It will soon be available when @IsmaelMartinez merges it. Until then you may get it from first link.

**Comment by Tsakatac** [comment]
Hello,

I confirm that I still have the issue and it is blocking because sharing a screen is a basic functionnality for Teams.

Thanks.

> Rambox 0.7.9
> Electron 11.4.10
> win32 x64 10.0.19043

**Comment by boguima** [comment]
Hello,

I confirm that I still have the issue and it is blocking because sharing a screen is a basic functionnality for Teams.

Thanks.

Version: 0.7.9
Platform: linux (x64)
Electron: 11.4.10

**Comment by erenoglu** [comment]
If wayland support is enabled in Chrome and pipewire is also enabled on the underlying system as well as Chrome flags, then Teams can share screen. At least that's how i use it on my Google Chrome under wayland.

**Comment by isabellerichard** [comment]
Hi, any news about this issue?

**Comment by apfelchips** [comment]
try [ferdi](https://github.com/getferdi/ferdi) it uses electron [15.4](https://github.com/getferdi/ferdi/blob/develop/package.json#L152) vs rambox's [11.4](https://github.com/ramboxapp/community-edition/blob/master/package.json#L211) and has no issue sharing the desktop in teams.

**Comment by yarons** [comment]
@apfelchips According to PR #3102 it doesn't look like it's related to electron version although I'm assuming there are many good reasons to upgrade electron anyway, is there an open issue or PR about that?

**Comment by teras** [comment]
Hello, I can see that this iissue is closed also for Discord. Is it expected to arrive on the community version? Since the commercial version seems to have fixed this.

https://github.com/ramboxapp/community-edition/issues/2655
