### ISSUE TITLE
Notifications are not saved in Notification Center

### ISSUE THREAD

**Issue by denbue** [ramboxapp/community-edition#479]
### Steps to reproduce

1. Receive a notification with a service in Rambox
2. Notification banner appears and pops up in Notification Center
3. Notification is removed after the banner disappears

### Expected behavior

Notification stays in Notifications Center after banner disappears

### Actual behavior

The notification doesnt stay in the Notifications Center

### ENVIRONMENT

Noticed with Slack and Messenger (only services I use, I guess its for every service)

> Rambox: v0.4.5

> OS: macOS Sierra

> Arch: x64

**Comment by denbue** [comment]
Hi @saenzramiro ,
I just saw that you labelled the issue with windows. I'm experiencing the problem on my Mac, though.

**Comment by saenzramiro** [comment]
Done! Sorry about that.

Windows and Mac notifications center seems to be a bug/feature-request for Electron. But I will keep this issue opened to add it in a future.

**Comment by mdacosta** [comment]
Hi!
Any news about this issue? It is still present in Rambox 0.6.2 on MacOS Sierra.

**Comment by gcsecsey** [comment]
Hi,

I'm interested in news as well. I can confirm that the issue is still present both on Windows 10 and MacOS Mojave.

**Comment by stanis64** [comment]
Hi, any news? It will be really nice if the notifications could stay in notifications center.

**Comment by saenzramiro** [comment]
Thank you @stanis64, I will try that and see if that fixes the problem.

**Comment by saenzramiro** [comment]
No luck, also made a research and this is an Electron bug (electron/electron#3916).
